### ISSUE TITLE
Form in footer area needs different style

### ISSUE THREAD

**Issue by tanelj** [Voog/design-bern#38]
![bern-form-in-footer](https://cloud.githubusercontent.com/assets/378755/8377362/57cdc6ca-1c19-11e5-9c0f-bb27ab286697.png)

**Comment by SSirjes** [comment]
1. Single choice and checkboxes background color is white, other input bg color grey. 
2. Input box-shadow and input background color is same = grey.
![screen shot 2015-11-13 at 10 12 48](https://cloud.githubusercontent.com/assets/13623224/11141560/25539352-89ef-11e5-8692-eb13a887a9f8.png)
