### ISSUE TITLE
Add design editor support

### ISSUE THREAD

**Issue by hennrunnel** [Voog/design-bern#50]

**Comment by SSirjes** [comment]
* [ ] **Main styles - Secondary color don't apply to active menu item**

![screen shot 2016-06-02 at 15 12 07](https://cloud.githubusercontent.com/assets/13623224/15744416/847058fa-28d4-11e6-9a12-3937a67bbb9d.png)

**Comment by hennrunnel** [comment]
Paar tähelepanekut.

- [ ] Kaalu kas tasuks tõsta main styles > colors all "primary color" "third color"-iks. Esilehel muudab praegune "primary color" ainult footeri teksti värvi, mis jääb serva alla. Visuaalselt suuremad muudatused too ettepoole.

- [ ] "Headings" grupi elementidel pane font-size'il featured: true ja kasuta type: button asemel slaiderit

- [ ] "Alignment" drop-down menüü väärtus "center" peaks algama suure tähega. Sama ka "on" ja "off" väärtustega "Button" > "Border" all.

- [ ] Puudub tõlge "Form" grupis olevele "label_size" stringile.

- [ ] Kaota alajaotus "Forms" > "Buttons". Las nende nuppude stiili kontrollib "Buttons" grupp
